services:
  - type: web
    name: sistema-produtos
    runtime: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-produtos-db
          property: connectionString
      - key: APP_KEY
        generateValue: true
    buildCommand: |
      cd src && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT

databases:
  - name: sistema-produtos-db
    plan: free
    databaseName: laravel
    user: laravel_user
